### ISSUE TITLE
Generated firmware rootfs detected as yaffs

### ISSUE THREAD

**Issue by Troll338cz** [kr105/tclinux-studio#2]
All sirmwares that are build useing original/extarcted squashfs are reporting it as yaffs resulting in kernel panic.

Original firmware mounting rootfs:
```
VFS: Mounted root (squashfs filesystem) readonly on device 31:3.
``` 
Custom firmware mounting rootfs:
```
s_magic err
failed_mount err=24
FAT: utf8 is not a recommended IO charset for FAT filesystems, filesystem will be case sensitive!
yaffs: dev is 32505859 name is "mtdblock3" ro
yaffs: passed flags ""
VFS: Mounted root (yaffs filesystem) readonly on device 31:3.
Freeing unused kernel memory: 212k freed
Kernel panic - not syncing: No init found. 
``` 
I'm not expecting any kind of help i just want to know if this is issue with the tool or the rootfs im createing.

**Comment by kr105** [comment]
I know this answer comes very late but I didn't check this repo before. I enabled global notifications so I never miss anything again.

Just to anyone checking in the future, this tool doesn't modify the rootfs file at all so probably the rootfs file you created is missing some flags or it is failing another check in the firmware itself.

For any unknown and weird problem like this, I suggest first doing a test with the `-t` flag to view the firmware setttings, then extract `-e` the rootfs and kernel binaries and imediately recreate the original firmware file with `-c` using exactly the same settings and files as the original firmware. Finally, check the hash of both the original firmware and the new generated file to see if they match. If they don't, it means that your firmware file is using a variation of this header that I am not supporting or using the `unk1` or `reserved` fields in the `tcl_header` struct.

If so, it would be useful to get a sample of such firmware file to analyze it and see if I can add support for that here.

I will close this issue, if you still have this problem, feel free to reopen it or open a new one.
